### ISSUE TITLE
Sugerencia cerradura alomantica

### ISSUE THREAD

**Issue by Sanfre0** [SteelCodeTeam/Metallics-Arts#46]
Un bloque que emita una señal de redstone dependiendo de si empujas o tiras de el

**Comment by Didaco795** [comment]
De lo poco que estuve en el servidor anterior, recuerdo que el mod incluía una palanca y unos botones que necesitabas de acero/hierro o peltre para accionarlas. Podríamos implementar algo así

**Comment by Sanfre0** [comment]
algo rollo, palanca cubierta de metal o botón cubierto de metal, poder activar los cables trampa tambien estaria guay

**Comment by SteelCodeTeam** [comment]
En las próximas versiones podréis ver una primera interacción de la redstone y la alomancia interactuando.

Probablemente en la 1.6.0 tendréis una primera versión. 

Muchas gracias por vuestras ideas.

¡Nos vemos en las brumas!
