### ISSUE TITLE
better hematology description

### ISSUE THREAD

**Issue by najlitarvan** [SteelCodeTeam/Metallics-Arts#56]
currently there is no proper information on how to use the spikes ingame, this is my suggestion for a text that could be used.
Metal spikes are used to steal powers from other players, each spike can steal either the allomantic or ferualcmenic power the metal it is made from represents. 
How to use: hit a player with the spike and there is a chance you get an inbued spike or that it breaks. Once the spike has been inbued, you then have to ask a second person to hit you with that spike to get that power

**Comment by rudahee** [comment]
Books update in new pre-release, in next 1.6.0 release version will be fixed.
