### ISSUE TITLE
better explanation for ferualchemy

### ISSUE THREAD

**Issue by najlitarvan** [SteelCodeTeam/Metallics-Arts#57]
1. 1. while i am aware of what i metalmind is, the name is never used when describing the bands and rings in the patchouli books, i would reccomend adding a note to the ring and band sections saying: they are  also called metalminds
2. this might be wrong if it is intentional, but the book calls it taping, but almost all metals except for bronze use the term decanting, i would reccomend commiting to only one term.
3. some have their storing/tapping description swapped, (pewter says that you gain strenght when storing and weakness when tapping, but it is opposite, atium is the same thing):
Atium
pewter

**Comment by rudahee** [comment]
Books update in pre-release, final solve in next 1.6.0 release version
