### ISSUE TITLE
[1.19.2] - Cannot load world with Metallic Arts Installed

### ISSUE THREAD

**Issue by ToxinZangoose** [SteelCodeTeam/Metallics-Arts#62]
When creating or joining a world, it will barely load past the joining world stage then crash and attempt to save the world.

1. Install Metallic Arts
2. Click 'Create World'
3. Wait
4. World crashes after attempting to save.

I really love the Mistborn/Brandon Sanderson series and would love to try it out in Minecraft.

 - OS: Windows 10
 - Browser [e.g. Microsoft Edge]
 - Graphic Card info: NVidia GeForce 2060 Super

Here is the crash report.
[crash-2023-02-19_13.25.50-client.txt](https://github.com/SteelCodeTeam/Metallics-Arts/files/10777747/crash-2023-02-19_13.25.50-client.txt)

**Comment by SteelCodeTeam** [comment]
Hi Toxin Zangoose! 

We had already seen this problem, it is a matter of the latest version of the forge that gives problems, and I doubt that we will have time to review it.

But try installing an older version of forge and it should work, 43.2.3 should suffice.

If the problem still persists, do not hesitate to let us know. ^^
