### ISSUE TITLE
Lanzamonedas

### ISSUE THREAD

**Issue by Ritterwind** [SteelCodeTeam/Metallics-Arts#65]
Un arma de lanzamonedas con un funcionamiento parecido al arco vanilla del minecraft. Añadiria armas propias del mod y casa bastante bien pues es algo que se usa mucho en los libros.

Tambien podria darse la opcion (manteniendo control como hay ahora mismo en el juego por ejemplo) de salir disparado en direccion contraria a la moneda, esto podria dar una mejor sensacion de "vuelo" a la actual pues seria mas facil proyectarte en diferentes direcciones y controlar mas tu velocidad.

Tambien podria estar bien que fueran interactuables mientras estan en vuelo, pudiendolas frenar o desviar con poderes alomanticos.

**Comment by SteelCodeTeam** [comment]
Buenas.

Estamos trabajando en ello, En la versión 1.6.0 podrás ver una primera implementación, también, si quieres testear lo que vamos haciendo, puedes bajar las betas desde aquí o desde curseforge, o pedirnos mas información a través de discord.

Espero que te gusten las novedades. ¡Nos vemos en las brumas!
