### ISSUE TITLE
Algunas sugerencias

### ISSUE THREAD

**Issue by dimonpi** [SteelCodeTeam/Metallics-Arts#67]
El mod es de los mejores que he visto nunca en minecraft, tengo algunas sugerencias que si bien no son importantes estaría guay ver en un futuro:
1.  Una de las principales mejoras a realizar sería un mejor bindeo de los poderes en general (creo que están trabajando en ello). De manera que pueda activar el acero pulsando la "Q" y desactivarlo volviéndolo a pulsar, por ejemplo.
2. Otra sugerencia es aumentar la duración del estaño alomántico. Como se ve a lo largo de todo el lore de mistborn, el estaño es uno de los metales que permiten un mayor uso continuado, hasta el punto de que con un solo vial podías aguantar todo el día.
3. Se podrían añadir algunos cuantos detalles guays a la hora de interactuar con ciertos metales: Si quemas oro y electrum que te aparezcan dos fantasmas (versiones tuyas, como el mítico sistema antihackeo que hay para el pvp) y que solo puedas ver tú. Al igual que si quemas peltre mucho tiempo que luego estés cansado. Otro detalle sería que si duermes teniendo activo alguno de los poderes alománticos vayas perdiendo poco a poco vida (en los libros dormir quemando metales es perjudicial para la salud), de manera que si te duermes quemando acero por ejemplo, sin haberlo desactivado antes, pierdas la primera vez medio corazón, la segunda un corazón entero... etc, de manera definitiva.
4. Por último estaría guay que añadieran una capa de nacido de la bruma que se pudiera llevar con cualquier armadura, que tuviera partículas o una animación cuando saltas o vuelas (no sé hasta qué punto es viable o si da mucho lag en un server).

Esas serían todas mis sugerencias, ninguna es urgente, pero son detalles que en futuras versiones sería un placer ver.

**Comment by dimonpi** [comment]
Una manera de implementar todos los metales en Singleplayer (aunque también para multiplayer) sería crear estructuras con inquisidores que se crearan por todo el mapa y si las superas puedas lootear uno o dos clavos y que el player se los pueda clavar a sí mismo. Así creas un sistema de exploración/looteo muy bueno.

**Comment by TobibusFate** [comment]
Buenas tardes @dimonpi 
Te voy siguiendo las recomendaciones:

1. El sistema de Keys ya esta implementado desde la primer versión, solo que en la ultima tuvimos un fallo, ya para la próxima beta estará reparado. Míralo en la sección de configuración de teclas de minecraft.
2. En cuanto al estaño, actualmente la banda de feruquimia y la carga máxima de alomancia es de 20 minutos, que es un día completo de minecraft 
3. Estamos trabajando en hacer algunas interacciones extra o mejores, nueva forma de funcionamiento para la hemalurgia, compounding y cosas así
4. La capa de bruma, al igual que armaduras hechas de aluminio y cosas asi están ya en nuestra hoja de ruta, pero aun no hemos tenido tiempo de agregarlos

Y respecto al single player, tenemos también en la hoja de ruta agregar estructuras y mobs (inquisidores) con los cuales luchar para conseguir poderes, o algunos tenderos que puedan venderlos también, pero lo mismo, aun no tenemos tiempo de agregarlo.

Saludos
