### ISSUE TITLE
Lots of broken recipes.

### ISSUE THREAD

**Issue by X66Herobrine66X** [SteelCodeTeam/Metallics-Arts#72]
My dudes, I think you need to take a long sweep through the mods recipes because there are a lot of recipes that shouldn't exist. Here are some of the one's I've found so far:
Lerasium/atium/ettmetal/malatium duplication:
![2023-05-26_23 54 24](https://github.com/SteelCodeTeam/Metallics-Arts/assets/31418501/e9990936-f2c1-4ea8-9ca3-82b3ef31936e)

Over half of the metals can be 'overfilled' in the vials:
![2023-05-26_23 54 42](https://github.com/SteelCodeTeam/Metallics-Arts/assets/31418501/58f154b6-9fa0-4dae-892b-7a0c729a5bd1)

**Comment by rudahee** [comment]
Hi. What version of the mod are you using?

**Comment by TobibusFate** [comment]
Hi @X66Herobrine66X 
This problem will be fixed in the next version ^^
Thanks for the warning
